version: '3.8'

services:
    frontend:
        build:
            context: ./packages/frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - backend-api
        env_file:
            - ./.env

    backend-api:
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        depends_on:
            - postgres
            - redis
        env_file:
            - ./.env

    ingestion-worker:
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        command: 'pnpm ts-node-dev --respawn --transpile-only src/workers/ingestion.worker.ts'
        depends_on:
            - postgres
            - redis
        env_file:
            - ./.env

    indexing-worker:
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        command: 'pnpm ts-node-dev --respawn --transpile-only src/workers/indexing.worker.ts'
        depends_on:
            - postgres
            - redis
        env_file:
            - ./.env

    postgres:
        image: postgres:15
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env

    redis:
        image: redis:7
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

    meilisearch:
        image: getmeili/meilisearch:v1.3
        ports:
            - '7700:7700'
        volumes:
            - meili_data:/meili_data
        env_file:
            - ./.env

volumes:
    postgres_data:
    redis_data:
    meili_data:
